const report = require('multiple-cucumber-html-reporter');
const path = require('path');
const fs = require('fs');

const jsonReportPath = path.join(__dirname, '../../test-results/cucumber-report.json');

if (!fs.existsSync(jsonReportPath)) {
  console.error('✗ No test report found. Please run tests first: npm run test:bdd');
  process.exit(1);
}

const reportGeneration = {
  jsonDir: path.join(__dirname, '../../test-results'),
  reportPath: path.join(__dirname, '../../test-results/cucumber-html-report'),
  openReportInBrowser: true,
  disableLog: true,
  pageTitle: 'Playwright + Cucumber BDD Test Report',
  reportName: 'Test Execution Report',
  pageFooter: '<div><p>Generated by Playwright + Cucumber BDD Framework</p></div>',
  displayDuration: true,
  durationInMS: true,
  metadata: {
    browser: {
      name: process.env.BROWSER || 'chrome',
    },
    device: 'Desktop',
    platform: {
      name: process.platform,
    },
  },
};

try {
  report.generate(reportGeneration);
  console.log('✓ HTML report generated successfully');
  console.log(`📊 Report location: test-results/cucumber-html-report/index.html`);
} catch (error) {
  console.error('✗ Failed to generate report:', error instanceof Error ? error.message : String(error));
  process.exit(1);
}

